words = ("apple", "river", "mountain", "cloud", "forest",
"ocean", "sunshine", "breeze", "flower", "garden",
"butterfly", "diamond", "rocket", "planet", "galaxy",
"pencil", "notebook", "window", "castle", "bridge",
"camera", "lantern", "thunder", "rainbow", "adventure",
"computer", "library", "guitar", "elephant",
"village", "tiger", "coffee", "island", "blanket",
"mirror", "journey", "candle", "parrot", "wallet",
"festival", "engine", "harvest", "kitchen", "magnet",
"pyramid", "scooter", "umbrella", "volcano", "whisper",
"yogurt", "zebra", "anchor", "basket", "circle",
"desert", "emerald", "feather", "hammer", "iceberg",
"jungle", "kitten", "ladder", "meadow", "nectar",
"orchard", "pebble", "quartz", "radar", "saddle",
"temple", "unicorn", "valley", "waterfall", "xylophone",
"yacht", "zeppelin", "artist", "button", "crystal",
"dragon", "energy", "fountain", "glacier", "helmet",
"insect", "jacket", "kangaroo", "legend", "meteor",
"needle", "orange", "penguin", "quiver", "robot",
"sunflower", "tunnel", "violet", "wanderer", "yearbook",
"zipper")